package toolsets

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/jazho76/devdeck/cli/internal/paths"
	"github.com/jazho76/devdeck/cli/internal/version"
)

var (
	commentRE = regexp.MustCompile(`--.*`)
	quotedRE  = regexp.MustCompile(`'([^']+)'`)
)

func Available(p paths.Paths) ([]string, error) {
	matches, err := filepath.Glob(filepath.Join(p.ToolsetsDir(), "*.lua"))
	if err != nil {
		return nil, err
	}

	names := make([]string, 0, len(matches))
	for _, m := range matches {
		names = append(names, strings.TrimSuffix(filepath.Base(m), ".lua"))
	}
	sort.Strings(names)

	if len(names) == 0 {
		return nil, fmt.Errorf("no toolsets found in %s", p.ToolsetsDir())
	}
	return names, nil
}

func Enabled(p paths.Paths, available []string) (map[string]bool, error) {
	data, err := os.ReadFile(activeOverride(p))
	if err != nil {
		if os.IsNotExist(err) {
			return map[string]bool{}, nil
		}
		return nil, err
	}
	return parseEnabled(data, available), nil
}

func Write(p paths.Paths, available []string, chosen map[string]bool) error {
	var b strings.Builder
	b.WriteString("-- Generated by devdeck " + version.Version + " - machine-local override, not tracked.\n")
	b.WriteString("return {\n")
	for _, n := range available {
		if chosen[n] {
			b.WriteString("  '" + n + "',\n")
		}
	}
	b.WriteString("}\n")
	return os.WriteFile(p.ToolsetsLocal(), []byte(b.String()), 0o644)
}

func activeOverride(p paths.Paths) string {
	if local := p.ToolsetsLocal(); fileExists(local) {
		return local
	}
	return p.ToolsetsDefault()
}

func parseEnabled(data []byte, available []string) map[string]bool {
	valid := make(map[string]bool, len(available))
	for _, n := range available {
		valid[n] = true
	}

	enabled := map[string]bool{}
	for _, m := range quotedRE.FindAllStringSubmatch(stripComments(data), -1) {
		if valid[m[1]] {
			enabled[m[1]] = true
		}
	}
	return enabled
}

func stripComments(data []byte) string {
	return commentRE.ReplaceAllString(string(data), "")
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}
