#!/usr/bin/env python3
"""Pick which nvim toolsets are enabled, writing a machine-local override."""

import argparse
import curses
import re
import sys
from pathlib import Path

CONFIG_DIR = Path(__file__).resolve().parent.parent / "nvim" / "lua" / "config"
TOOLSETS_DIR = CONFIG_DIR.parent / "toolsets"
DEFAULT_FILE = CONFIG_DIR / "toolsets-default.lua"
LOCAL_FILE = CONFIG_DIR / "toolsets-local.lua"


def enabled_in(path):
    if not path.is_file():
        return set()
    text = re.sub(r"--.*", "", path.read_text())
    return set(re.findall(r"'([^']+)'", text))


def write(names):
    lines = [
        "-- Generated by scripts/_configure-toolsets.py - machine-local override, not tracked.",
        "return {",
    ]
    lines += [f"  '{n}'," for n in names]
    lines.append("}\n")
    LOCAL_FILE.write_text("\n".join(lines))


def menu(stdscr, available, enabled):
    curses.use_default_colors()
    curses.curs_set(0)
    pos = 0
    while True:
        stdscr.erase()
        stdscr.addstr(
            0,
            0,
            "Toolsets  —  ↑/↓ move · space toggle · a all · n none · enter save · q cancel",
        )
        for i, name in enumerate(available):
            mark = "x" if name in enabled else " "
            attr = curses.A_REVERSE if i == pos else curses.A_NORMAL
            stdscr.addstr(i + 2, 2, f"[{mark}] {name}", attr)
        stdscr.refresh()

        key = stdscr.getch()
        if key in (curses.KEY_UP, ord("k")):
            pos = (pos - 1) % len(available)
        elif key in (curses.KEY_DOWN, ord("j")):
            pos = (pos + 1) % len(available)
        elif key == ord(" "):
            enabled ^= {available[pos]}
        elif key == ord("a"):
            enabled = set(available)
        elif key == ord("n"):
            enabled = set()
        elif key in (curses.KEY_ENTER, 10, 13):
            return enabled
        elif key == ord("q"):
            return None


def main():
    parser = argparse.ArgumentParser(
        description="Pick which nvim toolsets are enabled."
    )
    parser.add_argument(
        "--all", action="store_true", help="enable every toolset, non-interactively"
    )
    args = parser.parse_args()

    available = sorted(p.stem for p in TOOLSETS_DIR.glob("*.lua"))
    if not available:
        sys.exit(f"No toolsets found in {TOOLSETS_DIR}")

    if args.all:
        write(available)
        print(
            "Enabled all toolsets in nvim/lua/config/toolsets-local.lua - restart nvim to apply."
        )
        return

    enabled = enabled_in(LOCAL_FILE if LOCAL_FILE.is_file() else DEFAULT_FILE)
    chosen = curses.wrapper(menu, available, set(enabled) & set(available))

    if chosen is None:
        print("Cancelled. No changes.")
        return
    write([n for n in available if n in chosen])
    print("Saved nvim/lua/config/toolsets-local.lua - restart nvim to apply.")


if __name__ == "__main__":
    main()
