#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TOOLSETS_DIR="$REPO_DIR/nvim/lua/toolsets"
CONFIG_DIR="$REPO_DIR/nvim/lua/config"
DEFAULT_FILE="$CONFIG_DIR/toolsets-default.lua"
LOCAL_FILE="$CONFIG_DIR/toolsets-local.lua"
LOCAL_DISPLAY="nvim/lua/config/toolsets-local.lua"
TOOLSETS_SET=0
TOOLSETS=""

usage() {
  cat <<'USAGE'
Usage: scripts/configure-toolsets.sh [--toolsets name[,name...]] [--help]

Options:
  --toolsets LIST  Write a local toolset selection without opening fzf.
                   Use an empty value to disable all optional toolsets.
  --help           Show this help.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --toolsets)
      if [ "$#" -lt 2 ]; then
        echo "Missing value for --toolsets" >&2
        exit 1
      fi
      TOOLSETS="$2"
      TOOLSETS_SET=1
      shift 2
      ;;
    --toolsets=*)
      TOOLSETS="${1#--toolsets=}"
      TOOLSETS_SET=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

if [ ! -d "$TOOLSETS_DIR" ]; then
  echo "Toolsets directory not found: $TOOLSETS_DIR" >&2
  exit 1
fi

mapfile -t available < <(
  find "$TOOLSETS_DIR" -maxdepth 1 -type f -name '*.lua' -printf '%f\n' \
    | sed 's/\.lua$//' \
    | sort
)

if [ "${#available[@]}" -eq 0 ]; then
  echo "No toolsets found in $TOOLSETS_DIR" >&2
  exit 1
fi

has_toolset() {
  local toolset

  for toolset in "${available[@]}"; do
    [ "$toolset" = "$1" ] && return 0
  done

  return 1
}

write_toolsets() {
  local name

  {
    echo "-- Generated by scripts/configure-toolsets.sh — machine-local override, not tracked."
    echo "return {"
    for name in "${available[@]}"; do
      [ -n "${selected[$name]+x}" ] && printf "  '%s',\n" "$name"
    done
    echo "}"
  } >"$LOCAL_FILE"

  echo "Saved $LOCAL_DISPLAY"
  echo "Restart nvim to apply."
}

declare -A selected=()

if [ "$TOOLSETS_SET" -eq 1 ]; then
  if [ -n "$TOOLSETS" ]; then
    IFS=',' read -r -a requested <<<"$TOOLSETS"
    for name in "${requested[@]}"; do
      name="${name//[[:space:]]/}"
      [ -z "$name" ] && continue
      if ! has_toolset "$name"; then
        echo "Unknown toolset: $name" >&2
        echo "Available toolsets: ${available[*]}" >&2
        exit 1
      fi
      selected["$name"]=1
    done
  fi

  write_toolsets
  exit 0
fi

require_command fzf

read_list() {
  [ -f "$1" ] || return 0
  grep -oE "'[^']+'" "$1" | tr -d "'"
}

seed_file="$DEFAULT_FILE"
[ -f "$LOCAL_FILE" ] && seed_file="$LOCAL_FILE"
current="$(read_list "$seed_file" | paste -sd, -)"

start_bind=''
for i in "${!available[@]}"; do
  if read_list "$seed_file" | grep -Fxq "${available[$i]}"; then
    start_bind+="pos($((i + 1)))+toggle+"
  fi
done
start_bind+='pos(1)'

set +e
picked="$(
  printf '%s\n' "${available[@]}" | fzf \
    --multi \
    --sync \
    --reverse \
    --height='~100%' \
    --prompt='enable > ' \
    --header=$'Tab toggle · Ctrl-A all · Ctrl-D none · Enter save · Esc cancel\nEnabled now: '"${current:-(none)}" \
    --bind "start:${start_bind}" \
    --bind 'ctrl-a:select-all' \
    --bind 'ctrl-d:deselect-all'
)"
status=$?
set -e

if [ "$status" -ne 0 ]; then
  echo "Cancelled. No changes."
  exit 0
fi

while IFS= read -r name; do
  [ -n "$name" ] && selected["$name"]=1
done <<<"$picked"

write_toolsets
