#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TOOLSETS_DIR="$REPO_DIR/nvim/lua/toolsets"
CONFIG_DIR="$REPO_DIR/nvim/lua/config"
DEFAULT_FILE="$CONFIG_DIR/toolsets-default.lua"
LOCAL_FILE="$CONFIG_DIR/toolsets-local.lua"
LOCAL_DISPLAY="nvim/lua/config/toolsets-local.lua"

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

require_command fzf

if [ ! -d "$TOOLSETS_DIR" ]; then
  echo "Toolsets directory not found: $TOOLSETS_DIR" >&2
  exit 1
fi

# Available toolsets (the universe) — discovered from the toolsets/ modules so there
# is no hardcoded list to keep in sync.
mapfile -t available < <(
  find "$TOOLSETS_DIR" -maxdepth 1 -type f -name '*.lua' -printf '%f\n' \
    | sed 's/\.lua$//' \
    | sort
)

if [ "${#available[@]}" -eq 0 ]; then
  echo "No toolsets found in $TOOLSETS_DIR" >&2
  exit 1
fi

# Extract the quoted toolset names from a Lua list file. Only ever runs against the
# committed default and this script's own generated output.
read_list() {
  [ -f "$1" ] || return 0
  grep -oE "'[^']+'" "$1" | tr -d "'"
}

# Show the current selection (override if present, else committed default) in the header.
seed_file="$DEFAULT_FILE"
[ -f "$LOCAL_FILE" ] && seed_file="$LOCAL_FILE"
current="$(read_list "$seed_file" | paste -sd, -)"

set +e
selected="$(
  printf '%s\n' "${available[@]}" | fzf \
    --multi \
    --reverse \
    --height='~100%' \
    --prompt='enable > ' \
    --header=$'Tab toggle · Ctrl-A all · Ctrl-D none · Enter save · Esc cancel\nEnabled now: '"${current:-(none)}" \
    --bind 'ctrl-a:select-all' \
    --bind 'ctrl-d:deselect-all'
)"
status=$?
set -e

if [ "$status" -ne 0 ]; then
  echo "Cancelled. No changes."
  exit 0
fi

# Build a set from the selection, then emit in stable `available` order.
declare -A want=()
while IFS= read -r name; do
  [ -n "$name" ] && want["$name"]=1
done <<<"$selected"

{
  echo "-- Generated by scripts/configure-toolsets.sh — machine-local override, not tracked."
  echo "return {"
  for name in "${available[@]}"; do
    [ -n "${want[$name]+x}" ] && printf "  '%s',\n" "$name"
  done
  echo "}"
} >"$LOCAL_FILE"

echo "Saved $LOCAL_DISPLAY"
echo "Restart nvim to apply.  (Delete that file to revert to the committed default.)"
