#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TOOLSETS_DIR="$REPO_DIR/nvim/lua/toolsets"
CONFIG_DIR="$REPO_DIR/nvim/lua/config"
DEFAULT_FILE="$CONFIG_DIR/toolsets-default.lua"
LOCAL_FILE="$CONFIG_DIR/toolsets-local.lua"
LOCAL_DISPLAY="nvim/lua/config/toolsets-local.lua"

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

require_command fzf

if [ ! -d "$TOOLSETS_DIR" ]; then
  echo "Toolsets directory not found: $TOOLSETS_DIR" >&2
  exit 1
fi

mapfile -t available < <(
  find "$TOOLSETS_DIR" -maxdepth 1 -type f -name '*.lua' -printf '%f\n' \
    | sed 's/\.lua$//' \
    | sort
)

if [ "${#available[@]}" -eq 0 ]; then
  echo "No toolsets found in $TOOLSETS_DIR" >&2
  exit 1
fi

# Naive grep parse is fine: only ever reads the committed default or our own output.
read_list() {
  [ -f "$1" ] || return 0
  grep -oE "'[^']+'" "$1" | tr -d "'"
}

seed_file="$DEFAULT_FILE"
[ -f "$LOCAL_FILE" ] && seed_file="$LOCAL_FILE"

declare -A enabled=()
while IFS= read -r name; do
  [ -n "$name" ] && enabled["$name"]=1
done < <(read_list "$seed_file")

current="$(read_list "$seed_file" | paste -sd, -)"

# fzf can't pre-mark items, so pre-select the enabled toolsets via the start event:
# pos(N) jumps to the Nth item, toggle marks it. --sync ensures the list is loaded first.
start_bind=''
for i in "${!available[@]}"; do
  [ -n "${enabled[${available[$i]}]+x}" ] && start_bind+="pos($((i + 1)))+toggle+"
done
start_bind+='pos(1)'

set +e
selected="$(
  printf '%s\n' "${available[@]}" | fzf \
    --multi \
    --sync \
    --reverse \
    --height='~100%' \
    --prompt='enable > ' \
    --header=$'Tab toggle · Ctrl-A all · Ctrl-D none · Enter save · Esc cancel\nEnabled now: '"${current:-(none)}" \
    --bind "start:${start_bind}" \
    --bind 'ctrl-a:select-all' \
    --bind 'ctrl-d:deselect-all'
)"
status=$?
set -e

if [ "$status" -ne 0 ]; then
  echo "Cancelled. No changes."
  exit 0
fi

declare -A want=()
while IFS= read -r name; do
  [ -n "$name" ] && want["$name"]=1
done <<<"$selected"

{
  echo "-- Generated by scripts/configure-toolsets.sh — machine-local override, not tracked."
  echo "return {"
  for name in "${available[@]}"; do
    [ -n "${want[$name]+x}" ] && printf "  '%s',\n" "$name"
  done
  echo "}"
} >"$LOCAL_FILE"

echo "Saved $LOCAL_DISPLAY"
echo "Restart nvim to apply.  (Delete that file to revert to the committed default.)"
